--- #YAML:1.0
name:               Config-Simple-Extended
version:            0.09
abstract:           Extend Config::Simple w/ Configuration Inheritance, chosen by URL
author:
    - Hugh Esco <hesco@campaignfoundations.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Config::Simple:    0
    Data::Dumper:      0
    Test:              0
    Test::Deep:        0
    Test::More:        0
    Text::ParseWords:  0
    UNIVERSAL:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
